#!/usr/bin/env bash
# installer/install.sh
#
# Part of https://github.com/manojvermamv/continuous-code-auditor — by Manoj Verma
#
# Installs continuous-code-auditor for scheduled, unattended execution.
#
# This script assumes the skill folder is already sitting where you want it
# to live long-term (e.g. you `git clone`d it to /opt/auditor/continuous-code-auditor).
# It does NOT copy itself elsewhere — it configures things in place and
# points your chosen agent CLI and scheduler at this location.
#
# Usage (flags, for scripted/non-interactive installs):
#   installer/install.sh \
#     --agent-cli opencode|claude-code|gemini-cli|codex-cli|hermes \
#     --project /srv/your-project \
#     --audit-target "." \
#     --model "provider/model-id" \
#     --log-dir /opt/auditor/logs \
#     --scope personal|project \
#     --schedule systemd|cron|none
#
# --audit-target accepts a single file, a space-separated list of files (quote
# it as one argument), or "." for the whole project tree — see
# config/auditor.conf.example for the exact semantics.
#
# Run with no flags for interactive prompts (defaults shown in brackets).
#
# What it does:
#   1. Writes config/auditor.conf from your answers.
#   2. For agent CLIs with native skill discovery (Claude Code, Gemini CLI,
#      Codex CLI, Hermes), symlinks this skill folder into that CLI's
#      skill directory (personal or project scope, your choice) — see
#      adapters/<cli>.md for exactly where. opencode has no confirmed
#      skill-directory convention, so this step is skipped for it (the
#      opencode runner attaches SKILL.md directly instead).
#   3. Creates the runtime directories this skill needs: $PROJECT/work,
#      $PROJECT/archives, and the log directory.
#   4. Optionally installs and enables the systemd service+timer, or adds a
#      cron entry, pointed at scripts/run_auditor.sh in this location.
#   5. Prints next steps — including running once manually before trusting
#      the schedule.

set -euo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILL_NAME="continuous-code-auditor"

AGENT_CLI=""
PROJECT=""
AUDIT_TARGET=""
MODEL_NAME=""
LOG_DIR=""
SCOPE=""
SCHEDULE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --agent-cli) AGENT_CLI="$2"; shift 2 ;;
    --project) PROJECT="$2"; shift 2 ;;
    --audit-target) AUDIT_TARGET="$2"; shift 2 ;;
    --model) MODEL_NAME="$2"; shift 2 ;;
    --log-dir) LOG_DIR="$2"; shift 2 ;;
    --scope) SCOPE="$2"; shift 2 ;;
    --schedule) SCHEDULE="$2"; shift 2 ;;
    -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

ask() {
  local prompt="$1" default="$2" var
  read -r -p "$prompt [$default]: " var
  echo "${var:-$default}"
}

echo "== continuous-code-auditor installer =="
echo "Installing from: $SKILL_DIR"
echo

if [[ -z "$AGENT_CLI" ]]; then
  echo "Which agent CLI will run this skill?"
  echo "  1) opencode"
  echo "  2) claude-code"
  echo "  3) gemini-cli"
  echo "  4) codex-cli"
  echo "  5) hermes"
  choice="$(ask "Enter 1-5" "1")"
  case "$choice" in
    1) AGENT_CLI="opencode" ;;
    2) AGENT_CLI="claude-code" ;;
    3) AGENT_CLI="gemini-cli" ;;
    4) AGENT_CLI="codex-cli" ;;
    5) AGENT_CLI="hermes" ;;
    *) AGENT_CLI="$choice" ;;
  esac
fi

if [[ ! -f "$SKILL_DIR/scripts/runners/run_with_${AGENT_CLI}.sh" ]]; then
  echo "No runner for AGENT_CLI=\"$AGENT_CLI\". Valid values: opencode, claude-code, gemini-cli, codex-cli, hermes." >&2
  exit 1
fi

[[ -z "$PROJECT" ]] && PROJECT="$(ask "Path to the audited project root" "/srv/your-project")"
[[ -z "$AUDIT_TARGET" ]] && AUDIT_TARGET="$(ask "What to audit — a file, space-separated files, or '.' for the whole tree (relative to PROJECT)" ".")"
[[ -z "$MODEL_NAME" ]] && MODEL_NAME="$(ask "Model id for $AGENT_CLI (see adapters/$AGENT_CLI.md for the expected format)" "CHANGE_ME-set-your-model-id")"
[[ -z "$LOG_DIR" ]] && LOG_DIR="$(ask "Directory for wrapper logs/state" "/opt/auditor/logs")"

echo
echo "-- writing config/auditor.conf --"
mkdir -p "$SKILL_DIR/config"
cat > "$SKILL_DIR/config/auditor.conf" <<CONF
# Generated by installer/install.sh on $(date -Iseconds)
# Full explanation of every setting: config/auditor.conf.example

AGENT_CLI="$AGENT_CLI"
MODEL_NAME="$MODEL_NAME"
PROJECT="$PROJECT"
AUDIT_TARGET="$AUDIT_TARGET"
LOG_DIR="$LOG_DIR"

# --- run limits ---
TIMEOUT_SECONDS=240
FAILURE_THRESHOLD=3

# --- resource gating ---
# Disk is a hard failure (needs a human); load/memory are self-clearing
# deferrals (exit 14, never trips the circuit breaker). See
# references/workspace-and-execution.md "Resource gating".
MIN_FREE_DISK_MB=100
MAX_LOAD_PER_CPU=4.0
# MIN_FREE_MEM_MB=512          # opt-in; uses MemAvailable

# --- logging ---
# Add "json" (e.g. "text,json") to also emit logs/auditor.jsonl for a log
# pipeline. auditor.log is always written either way.
LOG_FORMAT="text"

# --- retention (enforced in code as of v1.5.0) ---
# Archives cited by the findings register are never pruned. Set either to 0
# to disable. See references/workspace-and-execution.md.
ARCHIVE_RETENTION_COUNT=50
EXECUTION_LOG_MAX_LINES=5000

# --- watchdog ---
# How stale before the scheduler itself is presumed dead. The watchdog runs
# on its own timer and catches the one failure the circuit breaker can't.
WATCHDOG_MAX_STALE_MINUTES=30

# --- optional: lifetime spend cap (adapters that report cost; today: claude-code) ---
# CUMULATIVE_BUDGET_USD=50.00
CONF
echo "wrote $SKILL_DIR/config/auditor.conf"

echo
echo "-- creating runtime directories --"
mkdir -p "$PROJECT/work" "$PROJECT/archives" "$PROJECT/backups" "$LOG_DIR"
echo "created $PROJECT/work, $PROJECT/archives, $PROJECT/backups, $LOG_DIR"

# --- skill installation for CLIs with native skill discovery ---
install_skill_link() {
  local target_dir="$1"
  mkdir -p "$(dirname "$target_dir")"
  if [[ -e "$target_dir" || -L "$target_dir" ]]; then
    echo "note: $target_dir already exists — leaving it as-is. Remove it first if you want this installer to replace it."
    return
  fi
  ln -s "$SKILL_DIR" "$target_dir"
  echo "linked $target_dir -> $SKILL_DIR"
}

install_commands() {
  # $1 = source dir under commands/, $2 = target commands dir, $3 = extension
  local src="$1" target_dir="$2" ext="$3"
  [[ -d "$src" ]] || return 0
  mkdir -p "$target_dir"
  local f base installed=0
  for f in "$src"/*."$ext"; do
    [[ -e "$f" ]] || continue
    base="$(basename "$f")"
    if [[ -e "$target_dir/$base" ]]; then
      echo "note: $target_dir/$base already exists — leaving it as-is."
    else
      cp "$f" "$target_dir/$base"
      installed=$((installed + 1))
    fi
  done
  [[ "$installed" -gt 0 ]] && echo "installed $installed slash command(s) into $target_dir"
}

case "$AGENT_CLI" in
  claude-code|gemini-cli|codex-cli|hermes)
    [[ -z "$SCOPE" ]] && SCOPE="$(ask "Install scope: 'personal' (all projects) or 'project' (this project only)" "personal")"
    case "$AGENT_CLI" in
      claude-code) skills_dir_name=".claude/skills" ;;
      gemini-cli)  skills_dir_name=".gemini/skills" ;;
      codex-cli)   skills_dir_name=".codex/skills" ;;
      hermes)      skills_dir_name=".hermes/skills" ;;
    esac
    echo
    echo "-- installing skill for $AGENT_CLI ($SCOPE scope) --"
    if [[ "$SCOPE" == "project" ]]; then
      install_skill_link "$PROJECT/${skills_dir_name}/${SKILL_NAME}"
    else
      install_skill_link "$HOME/${skills_dir_name}/${SKILL_NAME}"
    fi
    if [[ "$AGENT_CLI" == "gemini-cli" && "$SCOPE" == "project" ]]; then
      echo "note: Gemini CLI requires the project workspace to be marked 'trusted' for project-scoped skills to load — run /trust once interactively in $PROJECT before relying on the unattended schedule. See adapters/gemini-cli.md."
    fi

    # Native slash-command registration — see commands/README.md. Only
    # Claude Code and Gemini CLI have a confirmed mechanism; the others
    # rely on SKILL.md's universal recognition fallback instead.
    case "$AGENT_CLI" in
      claude-code)
        if [[ "$SCOPE" == "project" ]]; then
          install_commands "$SKILL_DIR/commands/claude-code" "$PROJECT/.claude/commands" "md"
        else
          install_commands "$SKILL_DIR/commands/claude-code" "$HOME/.claude/commands" "md"
        fi
        ;;
      gemini-cli)
        if [[ "$SCOPE" == "project" ]]; then
          install_commands "$SKILL_DIR/commands/gemini-cli" "$PROJECT/.gemini/commands" "toml"
        else
          install_commands "$SKILL_DIR/commands/gemini-cli" "$HOME/.gemini/commands" "toml"
        fi
        ;;
    esac
    ;;
  opencode)
    echo
    echo "-- no skill-directory install needed for opencode --"
    echo "(this adapter attaches SKILL.md directly on every invocation — see adapters/opencode.md)"
    ;;
esac

# --- scheduling ---
echo
if [[ -z "$SCHEDULE" ]]; then
  echo "How should this run on a schedule?"
  echo "  1) systemd service + timer (recommended for a permanent 24x7 install)"
  echo "  2) cron"
  echo "  3) none (I'll wire it up myself)"
  choice="$(ask "Enter 1-3" "3")"
  case "$choice" in
    1) SCHEDULE="systemd" ;;
    2) SCHEDULE="cron" ;;
    *) SCHEDULE="none" ;;
  esac
fi

case "$SCHEDULE" in
  systemd)
    if [[ "$EUID" -ne 0 ]]; then
      echo "Installing systemd units requires root — re-run this installer with sudo, or install them yourself:"
      echo "  $SKILL_DIR/scripts/systemd/continuous-code-auditor.service          -> /etc/systemd/system/"
      echo "  $SKILL_DIR/scripts/systemd/continuous-code-auditor.timer            -> /etc/systemd/system/"
      echo "  $SKILL_DIR/scripts/systemd/continuous-code-auditor-watchdog.service -> /etc/systemd/system/"
      echo "  $SKILL_DIR/scripts/systemd/continuous-code-auditor-watchdog.timer   -> /etc/systemd/system/"
      echo "Edit ExecStart in both .service files to point at $SKILL_DIR first."
    else
      sed "s|/opt/auditor/continuous-code-auditor|$SKILL_DIR|g" \
        "$SKILL_DIR/scripts/systemd/continuous-code-auditor.service" > /etc/systemd/system/continuous-code-auditor.service
      cp "$SKILL_DIR/scripts/systemd/continuous-code-auditor.timer" /etc/systemd/system/continuous-code-auditor.timer
      sed "s|/opt/auditor/continuous-code-auditor|$SKILL_DIR|g" \
        "$SKILL_DIR/scripts/systemd/continuous-code-auditor-watchdog.service" > /etc/systemd/system/continuous-code-auditor-watchdog.service
      cp "$SKILL_DIR/scripts/systemd/continuous-code-auditor-watchdog.timer" /etc/systemd/system/continuous-code-auditor-watchdog.timer
      systemctl daemon-reload
      systemctl enable --now continuous-code-auditor.timer
      systemctl enable --now continuous-code-auditor-watchdog.timer
      echo "installed and enabled continuous-code-auditor.timer and continuous-code-auditor-watchdog.timer"
      echo "the watchdog runs independently — see references/workspace-and-execution.md 'Scheduler-liveness watchdog' for why it's a separate unit, not part of the main one."
      echo "review /etc/systemd/system/continuous-code-auditor.service — the User=auditor account must exist and be able to read $SKILL_DIR and write $PROJECT and $LOG_DIR."
    fi
    ;;
  cron)
    CRON_LINE="*/5 * * * * $SKILL_DIR/scripts/run_auditor.sh >> $LOG_DIR/cron.log 2>&1"
    WATCHDOG_CRON_LINE="*/10 * * * * $SKILL_DIR/scripts/watchdog.sh"
    ( crontab -l 2>/dev/null | grep -vF "$SKILL_DIR/scripts/run_auditor.sh" | grep -vF "$SKILL_DIR/scripts/watchdog.sh" ; echo "$CRON_LINE" ; echo "$WATCHDOG_CRON_LINE" ) | crontab -
    echo "installed cron entries:"
    echo "  $CRON_LINE"
    echo "  $WATCHDOG_CRON_LINE"
    echo "the watchdog runs independently of the main entry — see references/workspace-and-execution.md 'Scheduler-liveness watchdog'."
    ;;
  none)
    echo "Skipping scheduler setup. Point your scheduler of choice at:"
    echo "  $SKILL_DIR/scripts/run_auditor.sh   (the audit itself)"
    echo "  $SKILL_DIR/scripts/watchdog.sh      (detects a dead scheduler — run this on a SEPARATE schedule, see references/workspace-and-execution.md)"
    ;;
esac

echo
echo "== done =="
echo "Before trusting the schedule, run once manually and check the result:"
echo "  $SKILL_DIR/scripts/run_auditor.sh; echo \"exit: \$?\""
echo "  cat $LOG_DIR/auditor.log"
echo "See adapters/$AGENT_CLI.md for anything specific to your chosen CLI."
